[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
logfile = /var/log/odoo/odoo.log
log_level = info
admin_passwd = $pbkdf2-sha512$600000$Xct5z1lLSWmttdZ6jxGCkA$Q6Uo3i8GuNNiKIMrRU8AJMfhA1kbDD0BX9BkJpJeWsr7rW2uwhLkO7UEqp9rcZxFLLbqUsZi1v38SHivcy9b6Q

